import type { ManagedAgent, ManagedAgentBackend } from "@/shared/api/types";

export type RawManagedAgent = {
  pubkey: string;
  name: string;
  persona_id: string | null;
  runtime?: string | null;
  team_id?: string | null;
  relay_url: string;
  acp_command: string;
  agent_command: string;
  agent_command_override?: string | null;
  agent_args: string[];
  mcp_command: string;
  turn_timeout_seconds: number;
  idle_timeout_seconds: number | null;
  max_turn_duration_seconds: number | null;
  parallelism: number;
  system_prompt: string | null;
  instructions_changed_for_agent?: boolean;
  avatar_url?: string | null;
  model: string | null;
  model_source?: ManagedAgent["modelSource"];
  provider: string | null;
  persona_out_of_date: boolean;
  persona_orphaned: boolean;
  needs_restart: boolean;
  env_vars?: Record<string, string>;
  status: ManagedAgent["status"];
  pid: number | null;
  created_at: string;
  updated_at: string;
  last_started_at: string | null;
  last_stopped_at: string | null;
  last_exit_code: number | null;
  last_error: string | null;
  last_error_code: number | null;
  log_path: string;
  start_on_app_launch: boolean;
  auto_restart_on_config_change?: boolean;
  backend: ManagedAgentBackend;
  backend_agent_id: string | null;
  project_scope?: ManagedAgent["projectScope"];
  tool_requirements?: ManagedAgent["toolRequirements"];
  skills?: ManagedAgent["skills"];
  skills_changed_for_agent?: boolean;
  connection_bindings?: Record<string, string>;
  respond_to?: ManagedAgent["respondTo"];
  respond_to_allowlist?: string[];
};
